import { Branch, ServiceCategory, Service, Staff, StaffWorkingHours } from './types';

// ===== DEMO BRANCH =====
export const demoBranch: Branch = {
  id: 'branch-001',
  businessId: 'biz-001',
  name: 'Timmo Nails Berlin',
  slug: 'glamour-nails-berlin',
  address: 'Kurfürstendamm 123, 10711 Berlin',
  phone: '+49 30 1234567',
  currency: 'EUR',
  publicStaffSelection: true,
  minimumNoticeHours: 3,
  bookingWindowDays: 30,
  graceTimeMinutes: 30,
  slotIntervalMinutes: 30,
  absenceDeadlineTime: '22:00',
  isActive: true,
  createdAt: '2026-01-01T00:00:00Z',
};

// ═══════════════════════════════════════
//  CATEGORIES — 9 standard + 1 addon
// ═══════════════════════════════════════
export const demoCategories: ServiceCategory[] = [
  {
    id: 'cat-gel',
    branchId: 'branch-001',
    name: 'Neumodellage mit Gel',
    description: 'Gel-Neumodellage für natürliche und kreative Nägel',
    displayOrder: 1,
    isActive: true,
    conflictGroup: 'gel',
  },
  {
    id: 'cat-auffuellen-gel',
    branchId: 'branch-001',
    name: 'Auffüllen mit Gel',
    description: 'Gel-Auffüllung für bestehende Gel-Nägel',
    displayOrder: 2,
    isActive: true,
    conflictGroup: 'gel',
  },
  {
    id: 'cat-acryl',
    branchId: 'branch-001',
    name: 'Neumodellage mit Acryl',
    description: 'Acryl-Neumodellage für haltbare Nagelverstärkung',
    displayOrder: 3,
    isActive: true,
    conflictGroup: 'acryl',
  },
  {
    id: 'cat-auffuellen-acryl',
    branchId: 'branch-001',
    name: 'Auffüllen mit Acryl',
    description: 'Acryl-Auffüllung für bestehende Acryl-Nägel',
    displayOrder: 4,
    isActive: true,
    conflictGroup: 'acryl',
  },
  {
    id: 'cat-zehen',
    branchId: 'branch-001',
    name: 'Zehenmodellage',
    description: 'Zehennagelmodellage mit Gel oder Acryl',
    displayOrder: 5,
    isActive: true,
    requiresStaffAutoAssign: true,
  },
  {
    id: 'cat-mani',
    branchId: 'branch-001',
    name: 'Maniküre',
    description: 'Handpflege, Nagellack und Shellac',
    displayOrder: 6,
    isActive: true,
  },
  {
    id: 'cat-pedi',
    branchId: 'branch-001',
    name: 'Pediküre',
    description: 'Fußpflege, Nagellack und Shellac',
    displayOrder: 7,
    isActive: true,
    requiresStaffAutoAssign: true,
  },
  {
    id: 'cat-wimpern',
    branchId: 'branch-001',
    name: 'Wimpern',
    description: 'Wimpernverlängerung, Auffüllung und Ablösung',
    displayOrder: 8,
    isActive: true,
  },
  {
    id: 'cat-abloesung',
    branchId: 'branch-001',
    name: 'Ablösung',
    description: 'Professionelle Nagelablösung',
    displayOrder: 9,
    isActive: true,
  },
  {
    id: 'cat-zusatz',
    branchId: 'branch-001',
    name: 'Zusatzleistungen',
    description: 'Individuelle Zusatzangebote',
    displayOrder: 10,
    isActive: true,
  },
];

// ═══════════════════════════════════════════════════
//  SERVICES — hardcoded from PDF + addon category
//  Prices are realistic for Berlin market (EUR)
// ═══════════════════════════════════════════════════
export const demoServices: Service[] = [
  // ── Neumodellage mit Gel ──
  {
    id: 'svc-gel-natur',
    branchId: 'branch-001',
    categoryId: 'cat-gel',
    name: 'Natur',
    description: 'Natürliche Gel-Neumodellage ohne Farbe',
    durationMinutes: 45,
    price: 40,
    currency: 'EUR',
    displayOrder: 1,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    conflictGroup: 'gel',
    staffPriority: 'main_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-gel-farbe',
    branchId: 'branch-001',
    categoryId: 'cat-gel',
    name: 'Farbe / Glitzer / French',
    description: 'Gel-Neumodellage mit Farbe, Glitzer oder French-Design',
    durationMinutes: 45,
    price: 48,
    currency: 'EUR',
    displayOrder: 2,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    conflictGroup: 'gel',
    staffPriority: 'main_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-gel-babyboomer',
    branchId: 'branch-001',
    categoryId: 'cat-gel',
    name: 'Verlauf (Babyboomer)',
    description: 'Gel-Neumodellage mit elegantem Babyboomer-Verlauf',
    durationMinutes: 45,
    price: 52,
    currency: 'EUR',
    displayOrder: 3,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    conflictGroup: 'gel',
    staffPriority: 'main_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-gel-design',
    branchId: 'branch-001',
    categoryId: 'cat-gel',
    name: 'Design / Extra',
    description: 'Zusätzliches Nageldesign zur Gel-Neumodellage',
    durationMinutes: 15,
    price: 10,
    currency: 'EUR',
    displayOrder: 4,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    isAddon: true,
    conflictGroup: 'gel',
    staffPriority: 'main_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },

  // ── Auffüllen mit Gel ──
  {
    id: 'svc-auffgel-natur',
    branchId: 'branch-001',
    categoryId: 'cat-auffuellen-gel',
    name: 'Natur',
    description: 'Gel-Auffüllung ohne Farbe',
    durationMinutes: 45,
    price: 35,
    currency: 'EUR',
    displayOrder: 1,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    conflictGroup: 'gel',
    staffPriority: 'main_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-auffgel-farbe',
    branchId: 'branch-001',
    categoryId: 'cat-auffuellen-gel',
    name: 'Farbe / Glitzer / French',
    description: 'Gel-Auffüllung mit Farbe, Glitzer oder French-Design',
    durationMinutes: 45,
    price: 43,
    currency: 'EUR',
    displayOrder: 2,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    conflictGroup: 'gel',
    staffPriority: 'main_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-auffgel-babyboomer',
    branchId: 'branch-001',
    categoryId: 'cat-auffuellen-gel',
    name: 'Verlauf (Babyboomer)',
    description: 'Gel-Auffüllung mit elegantem Babyboomer-Verlauf',
    durationMinutes: 45,
    price: 47,
    currency: 'EUR',
    displayOrder: 3,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    conflictGroup: 'gel',
    staffPriority: 'main_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-auffgel-design',
    branchId: 'branch-001',
    categoryId: 'cat-auffuellen-gel',
    name: 'Design / Extra',
    description: 'Zusätzliches Nageldesign zur Gel-Auffüllung',
    durationMinutes: 15,
    price: 10,
    currency: 'EUR',
    displayOrder: 4,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    isAddon: true,
    conflictGroup: 'gel',
    staffPriority: 'main_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },

  // ── Neumodellage mit Acryl ──
  {
    id: 'svc-acryl-natur',
    branchId: 'branch-001',
    categoryId: 'cat-acryl',
    name: 'Natur',
    description: 'Natürliche Acryl-Neumodellage ohne Farbe',
    durationMinutes: 45,
    price: 38,
    currency: 'EUR',
    displayOrder: 1,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    conflictGroup: 'acryl',
    staffPriority: 'main_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-acryl-farbe',
    branchId: 'branch-001',
    categoryId: 'cat-acryl',
    name: 'Farbe / Glitzer / French',
    description: 'Acryl-Neumodellage mit Farbe, Glitzer oder French-Design',
    durationMinutes: 45,
    price: 45,
    currency: 'EUR',
    displayOrder: 2,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    conflictGroup: 'acryl',
    staffPriority: 'main_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-acryl-babyboomer',
    branchId: 'branch-001',
    categoryId: 'cat-acryl',
    name: 'Verlauf (Babyboomer)',
    description: 'Acryl-Neumodellage mit elegantem Babyboomer-Verlauf',
    durationMinutes: 45,
    price: 48,
    currency: 'EUR',
    displayOrder: 3,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    conflictGroup: 'acryl',
    staffPriority: 'main_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-acryl-design',
    branchId: 'branch-001',
    categoryId: 'cat-acryl',
    name: 'Design / Extra',
    description: 'Zusätzliches Nageldesign zur Acryl-Neumodellage',
    durationMinutes: 15,
    price: 10,
    currency: 'EUR',
    displayOrder: 4,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    isAddon: true,
    conflictGroup: 'acryl',
    staffPriority: 'main_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },

  // ── Auffüllen mit Acryl ──
  {
    id: 'svc-auffacryl-natur',
    branchId: 'branch-001',
    categoryId: 'cat-auffuellen-acryl',
    name: 'Natur',
    description: 'Acryl-Auffüllung ohne Farbe',
    durationMinutes: 45,
    price: 33,
    currency: 'EUR',
    displayOrder: 1,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    conflictGroup: 'acryl',
    staffPriority: 'main_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-auffacryl-farbe',
    branchId: 'branch-001',
    categoryId: 'cat-auffuellen-acryl',
    name: 'Farbe / Glitzer / French',
    description: 'Acryl-Auffüllung mit Farbe, Glitzer oder French-Design',
    durationMinutes: 45,
    price: 40,
    currency: 'EUR',
    displayOrder: 2,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    conflictGroup: 'acryl',
    staffPriority: 'main_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-auffacryl-babyboomer',
    branchId: 'branch-001',
    categoryId: 'cat-auffuellen-acryl',
    name: 'Verlauf (Babyboomer)',
    description: 'Acryl-Auffüllung mit elegantem Babyboomer-Verlauf',
    durationMinutes: 45,
    price: 43,
    currency: 'EUR',
    displayOrder: 3,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    conflictGroup: 'acryl',
    staffPriority: 'main_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-auffacryl-design',
    branchId: 'branch-001',
    categoryId: 'cat-auffuellen-acryl',
    name: 'Design / Extra',
    description: 'Zusätzliches Nageldesign zur Acryl-Auffüllung',
    durationMinutes: 15,
    price: 10,
    currency: 'EUR',
    displayOrder: 4,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    isAddon: true,
    conflictGroup: 'acryl',
    staffPriority: 'main_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },

  // ── Zehenmodellage ──
  {
    id: 'svc-zehen-gel',
    branchId: 'branch-001',
    categoryId: 'cat-zehen',
    name: 'Mit Gel',
    description: 'Zehennagelmodellage mit Gel',
    durationMinutes: 45,
    price: 42,
    currency: 'EUR',
    displayOrder: 1,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    staffPriority: 'main_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-zehen-acryl',
    branchId: 'branch-001',
    categoryId: 'cat-zehen',
    name: 'Mit Acryl',
    description: 'Zehennagelmodellage mit Acryl',
    durationMinutes: 45,
    price: 42,
    currency: 'EUR',
    displayOrder: 2,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    staffPriority: 'main_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-zehen-design',
    branchId: 'branch-001',
    categoryId: 'cat-zehen',
    name: 'Design / Extra',
    description: 'Zusätzliches Design zur Zehenmodellage',
    durationMinutes: 15,
    price: 10,
    currency: 'EUR',
    displayOrder: 3,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    isAddon: true,
    staffPriority: 'main_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },

  // ── Maniküre ──
  {
    id: 'svc-mani-basic',
    branchId: 'branch-001',
    categoryId: 'cat-mani',
    name: 'Basic',
    description: 'Grundlegende Maniküre mit Feilen und Nagelpflege',
    durationMinutes: 15,
    price: 15,
    currency: 'EUR',
    displayOrder: 1,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    staffPriority: 'assistant_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-mani-lack',
    branchId: 'branch-001',
    categoryId: 'cat-mani',
    name: 'Mit Nagellack',
    description: 'Maniküre mit klassischem Nagellack',
    durationMinutes: 30,
    price: 25,
    currency: 'EUR',
    displayOrder: 2,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    staffPriority: 'assistant_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-mani-shellac',
    branchId: 'branch-001',
    categoryId: 'cat-mani',
    name: 'Mit Shellac',
    description: 'Maniküre mit langhaltendem Shellac-Lack',
    durationMinutes: 45,
    price: 35,
    currency: 'EUR',
    displayOrder: 3,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    staffPriority: 'conditional_assistant',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-mani-design',
    branchId: 'branch-001',
    categoryId: 'cat-mani',
    name: 'Design / Extra',
    description: 'Zusätzliches Design zur Maniküre',
    durationMinutes: 15,
    price: 10,
    currency: 'EUR',
    displayOrder: 4,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    isAddon: true,
    staffPriority: 'none',
    createdAt: '2026-01-01T00:00:00Z',
  },

  // ── Pediküre ──
  {
    id: 'svc-pedi-basic',
    branchId: 'branch-001',
    categoryId: 'cat-pedi',
    name: 'Basic',
    description: 'Grundlegende Pediküre mit Fußpflege',
    durationMinutes: 45,
    price: 28,
    currency: 'EUR',
    displayOrder: 1,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    staffPriority: 'assistant_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-pedi-lack',
    branchId: 'branch-001',
    categoryId: 'cat-pedi',
    name: 'Mit Nagellack',
    description: 'Pediküre mit klassischem Nagellack',
    durationMinutes: 45,
    price: 35,
    currency: 'EUR',
    displayOrder: 2,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    staffPriority: 'assistant_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-pedi-shellac',
    branchId: 'branch-001',
    categoryId: 'cat-pedi',
    name: 'Mit Shellac',
    description: 'Pediküre mit langhaltendem Shellac-Lack',
    durationMinutes: 45,
    price: 42,
    currency: 'EUR',
    displayOrder: 3,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    staffPriority: 'conditional_assistant',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-pedi-design',
    branchId: 'branch-001',
    categoryId: 'cat-pedi',
    name: 'Design / Extra',
    description: 'Zusätzliches Design zur Pediküre',
    durationMinutes: 15,
    price: 10,
    currency: 'EUR',
    displayOrder: 4,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    isAddon: true,
    staffPriority: 'none',
    createdAt: '2026-01-01T00:00:00Z',
  },

  // ── Wimpern ──
  {
    id: 'svc-wimpern-verl',
    branchId: 'branch-001',
    categoryId: 'cat-wimpern',
    name: 'Wimpernverlängerung',
    description: 'Professionelle Wimpernverlängerung',
    durationMinutes: 60,
    price: 70,
    currency: 'EUR',
    displayOrder: 1,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    staffPriority: 'main_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-wimpern-fuell',
    branchId: 'branch-001',
    categoryId: 'cat-wimpern',
    name: 'Wimpernfüllung',
    description: 'Auffüllung bestehender Wimpernverlängerung',
    durationMinutes: 45,
    price: 45,
    currency: 'EUR',
    displayOrder: 2,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    staffPriority: 'main_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-wimpern-abloesung',
    branchId: 'branch-001',
    categoryId: 'cat-wimpern',
    name: 'Wimpernablösung',
    description: 'Schonende Entfernung der Wimpernverlängerung',
    durationMinutes: 30,
    price: 15,
    currency: 'EUR',
    displayOrder: 3,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    staffPriority: 'conditional_assistant',
    createdAt: '2026-01-01T00:00:00Z',
  },

  // ── Ablösung ──
  {
    id: 'svc-abloesung',
    branchId: 'branch-001',
    categoryId: 'cat-abloesung',
    name: 'Ablösung',
    description: 'Professionelle Ablösung von Gel- oder Acrylnägeln',
    durationMinutes: 15,
    price: 12,
    currency: 'EUR',
    displayOrder: 1,
    isActive: true,
    hasAppointments: false,
    type: 'standard',
    staffPriority: 'assistant_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },

  // ── Zusatzleistungen (addon) ──
  {
    id: 'svc-zusatz-massage-30',
    branchId: 'branch-001',
    categoryId: 'cat-zusatz',
    name: 'Massage 30 Min',
    description: 'Entspannende Hand- oder Fußmassage (30 Minuten)',
    durationMinutes: 30,
    price: 25,
    currency: 'EUR',
    displayOrder: 1,
    isActive: true,
    hasAppointments: false,
    type: 'addon',
    staffPriority: 'assistant_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-zusatz-massage-45',
    branchId: 'branch-001',
    categoryId: 'cat-zusatz',
    name: 'Massage 45 Min',
    description: 'Entspannende Hand- oder Fußmassage (45 Minuten)',
    durationMinutes: 45,
    price: 35,
    currency: 'EUR',
    displayOrder: 2,
    isActive: true,
    hasAppointments: false,
    type: 'addon',
    staffPriority: 'assistant_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-zusatz-massage-60',
    branchId: 'branch-001',
    categoryId: 'cat-zusatz',
    name: 'Massage 60 Min',
    description: 'Entspannende Hand- oder Fußmassage (60 Minuten)',
    durationMinutes: 60,
    price: 45,
    currency: 'EUR',
    displayOrder: 3,
    isActive: true,
    hasAppointments: false,
    type: 'addon',
    staffPriority: 'assistant_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-zusatz-headspa-30',
    branchId: 'branch-001',
    categoryId: 'cat-zusatz',
    name: 'Head Spa 30 Min',
    description: 'Entspannendes Head Spa für Kopfhaut und Haare (30 Minuten)',
    durationMinutes: 30,
    price: 30,
    currency: 'EUR',
    displayOrder: 4,
    isActive: true,
    hasAppointments: false,
    type: 'addon',
    staffPriority: 'assistant_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-zusatz-headspa-45',
    branchId: 'branch-001',
    categoryId: 'cat-zusatz',
    name: 'Head Spa 45 Min',
    description: 'Entspannendes Head Spa für Kopfhaut und Haare (45 Minuten)',
    durationMinutes: 45,
    price: 40,
    currency: 'EUR',
    displayOrder: 5,
    isActive: true,
    hasAppointments: false,
    type: 'addon',
    staffPriority: 'assistant_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-zusatz-headspa-60',
    branchId: 'branch-001',
    categoryId: 'cat-zusatz',
    name: 'Head Spa 60 Min',
    description: 'Entspannendes Head Spa für Kopfhaut und Haare (60 Minuten)',
    durationMinutes: 60,
    price: 55,
    currency: 'EUR',
    displayOrder: 6,
    isActive: true,
    hasAppointments: false,
    type: 'addon',
    staffPriority: 'assistant_staff',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-zusatz-deluxe-mani',
    branchId: 'branch-001',
    categoryId: 'cat-zusatz',
    name: 'Deluxe Maniküre',
    description: 'Premium-Handpflege mit Peeling, Maske und Massage',
    durationMinutes: 60,
    price: 55,
    currency: 'EUR',
    displayOrder: 7,
    isActive: true,
    hasAppointments: false,
    type: 'addon',
    staffPriority: 'none',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'svc-zusatz-deluxe-pedi',
    branchId: 'branch-001',
    categoryId: 'cat-zusatz',
    name: 'Deluxe Pediküre',
    description: 'Premium-Fußpflege mit Peeling, Maske und Massage',
    durationMinutes: 75,
    price: 65,
    currency: 'EUR',
    displayOrder: 8,
    isActive: true,
    hasAppointments: false,
    type: 'addon',
    staffPriority: 'none',
    createdAt: '2026-01-01T00:00:00Z',
  },
];

// ═══════════════════════════════════════════════════
//  Service ID groups for staff assignment
// ═══════════════════════════════════════════════════
const allStandardIds = demoServices.filter(s => s.type === 'standard').map(s => s.id);
const gelAcrylIds = demoServices
  .filter(s => ['cat-gel', 'cat-acryl', 'cat-auffuellen-gel', 'cat-auffuellen-acryl', 'cat-zehen'].includes(s.categoryId))
  .map(s => s.id);
const auffuellenIds = demoServices
  .filter(s => ['cat-auffuellen-gel', 'cat-auffuellen-acryl'].includes(s.categoryId))
  .map(s => s.id);
const maniPediIds = demoServices
  .filter(s => ['cat-mani', 'cat-pedi'].includes(s.categoryId))
  .map(s => s.id);
const wimpernIds = demoServices
  .filter(s => s.categoryId === 'cat-wimpern')
  .map(s => s.id);
const abloesungIds = demoServices
  .filter(s => s.categoryId === 'cat-abloesung')
  .map(s => s.id);

// ===== STAFF =====
export const demoStaff: Staff[] = [
  {
    id: 'staff-001',
    branchId: 'branch-001',
    userUid: null,
    name: 'Lisa Nguyen',
    initials: 'LN',
    role: 'manager',
    staffType: 'main',
    serviceIds: allStandardIds,
    displayOrder: 1,
    status: 'active',
    hasAppointments: false,
    rating: 4.9,
    languages: ['DE', 'EN', 'VI'],
    title: 'Senior Nail Technician',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'staff-002',
    branchId: 'branch-001',
    userUid: null,
    name: 'Anna Schmidt',
    initials: 'AS',
    role: 'staff',
    staffType: 'junior',
    serviceIds: [...maniPediIds, ...abloesungIds],
    displayOrder: 2,
    status: 'active',
    hasAppointments: false,
    rating: 4.7,
    languages: ['DE', 'EN'],
    title: 'Maniküre & Pediküre Spezialistin',
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'staff-003',
    branchId: 'branch-001',
    userUid: null,
    name: 'Minh Tran',
    initials: 'MT',
    role: 'staff',
    staffType: 'main',
    serviceIds: [...gelAcrylIds, ...abloesungIds],
    displayOrder: 3,
    status: 'active',
    hasAppointments: false,
    rating: 4.8,
    languages: ['DE', 'VI'],
    title: 'Gel & Acryl Spezialist',
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'staff-004',
    branchId: 'branch-001',
    userUid: null,
    name: 'Sophie Weber',
    initials: 'SW',
    role: 'staff',
    staffType: 'junior',
    serviceIds: [...wimpernIds, ...maniPediIds],
    displayOrder: 4,
    status: 'active',
    hasAppointments: false,
    rating: 4.6,
    languages: ['DE'],
    title: 'Wimpern & Pediküre Spezialistin',
    createdAt: '2026-03-01T00:00:00Z',
  },
];

// ===== WORKING HOURS =====
export const demoWorkingHours: StaffWorkingHours[] = demoStaff.flatMap((staff) =>
  [0, 1, 2, 3, 4, 5].map((day) => ({
    id: `wh-${staff.id}-${day}`,
    staffId: staff.id,
    dayOfWeek: day,
    startTime: '09:00',
    endTime: day === 5 ? '16:00' : '18:00',
    isWorking: true,
  }))
);

// ===== HELPER: Generate time slots for a given date =====
export function generateDemoTimeSlots(
  date: string,
  staffId?: string
): { time: string; available: boolean; status: 'available' | 'held' | 'booked' | 'request_only' }[] {
  const slots: { time: string; available: boolean; status: 'available' | 'held' | 'booked' | 'request_only' }[] = [];
  const dateObj = new Date(date);
  const dayOfWeek = (dateObj.getDay() + 6) % 7; // Convert to Mon=0

  if (dayOfWeek === 6) return []; // Sunday

  const endHour = dayOfWeek === 5 ? 16 : 18;

  for (let hour = 9; hour < endHour; hour++) {
    for (const min of [0, 30]) {
      const time = `${hour.toString().padStart(2, '0')}:${min.toString().padStart(2, '0')}`;
      // Pseudo-random availability based on date + time + staffId
      const seed = (dateObj.getDate() * 100 + hour * 10 + min + (staffId ? staffId.charCodeAt(staffId.length - 1) : 0)) % 10;
      const isRequestOnly = seed < 4; // 40% of slots are already booked by others, showing as requestable waitlist
      const isHeld = seed === 4;       // 10% are temporarily locked/held
      
      slots.push({
        time,
        available: !isHeld, // held slots are locked; both free and booked slots are clickable!
        status: isHeld ? 'held' : isRequestOnly ? 'request_only' : 'available',
      });
    }
  }
  return slots;
}
