sonar.projectKey=Daeyang-Sea_timmo-hrm-backend
sonar.organization=daeyang-sea

sonar.sources=src

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.*,**/*.spec.*,**/coverage/**,**/*.config.*
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
